services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/meuBancoDados
      - SESSION_KEY=Dg4251gH1IDCMWfHSg7o7fS1zlWDE

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    command: mongod --logpath /dev/null --logappend --quiet 